title: dev-human
subtitle: Non-technical content for humans who code
domain_url: http://dev-human.com
google_analytics_tracking_id: UA-50664641-1
default_date_format: M d, Y

#######################################################################################################
# The authors. Include your info here, under the "authors" key, using the following template:
#
#  erikaheidi:
#      name: Your Name
#      url: http://yourURL.com
#      avatar: http://url.to.a.valid/avatar.jpeg
#      twitter: http://twitter.com/erikaheidi
#      googleplus: https://plus.google.com/102734777555057691872
#      bio: this is a short bio, it should not be so long, just a quick info that defines you.
#
# Please provide at least "name" and "bio" . The googleplus url is useful to show your author info
# on Google search results.
#######################################################################################################
authors:
  erikaheidi:
      name: Erika Heidi
      url: http://erikaheidi.com
      avatar: https://pbs.twimg.com/profile_images/478827743363088384/eMQQzPVF.jpeg
      twitter: http://twitter.com/erikaheidi
      googleplus: https://plus.google.com/102734777555057691872
      bio: independent web developer && open source enthusiast. sometimes writer, sometimes speaker. loves cats, elephpants and unicorns.
  cordoval:
      name: Luis Cordova
      url: http://pilotci.com
      avatar: https://pbs.twimg.com/profile_images/454329885859647488/t4PNNYMm.png
      twitter: http://twitter.com/cordoval
      bio: Gush lead developer, Bldr.io team member, author, translator, sometimes speaker too, like simplicity and clean code
  matthiasnoback:
      name: Matthias Noback
      url: http://php-and-symfony.matthiasnoback.nl
      avatar: https://pbs.twimg.com/profile_images/1591397394/matthias-noback.jpg
      twitter: http://twitter.com/matthiasnoback
      bio: PHP developer, writer, speaker, father.
  ramondelafuente:
      name: Ramon de la Fuente
      url: http://future500.nl
      avatar: https://pbs.twimg.com/profile_images/1320805243/ramon.jpg
      twitter: http://twitter.com/f_u_e_n_t_e
      bio: Company owner, Developer, User group organizer and family man (not necessarily in that order)
  meadsteve:
      name: Steve Brazier
      url: http://meadsteve.github.io/
      avatar: https://pbs.twimg.com/profile_images/458936525338587140/bjZT3Y8R_400x400.png
      twitter: http://twitter.com/meadsteve
      bio: Standard Human. Reasonable Developer. Poorly co-ordinated.
  geeh:
      name: Gary Hockin
      url: http://blog.hock.in/
      avatar: https://www.gravatar.com/avatar/e61ae7dfad370ba47a72f79418160f51?s=180&d=mm&r=g
      twitter: http://twitter.com/geeh
      bio: Roave man, conference speaker, pretend developer. Pool player.
